LABEL := "oracular"

default:
    @just --list

list:
    #!/usr/bin/env nu
    multipass list --format json | from json | get list | reject release

new NAME:
    multipass launch {{LABEL}} --name {{NAME}} --cloud-init user-data.yml
