#cloud-config
password: "12345"
chpasswd:
  expire: False

users:
- name: default
  plain_text_passwd: 12345

allow_public_ssh_keys: true
disable_root: false
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding
ssh_authorized_keys: [ "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOvBw3klXzVq5oTXtS061cfcGEjHWflPZNRBRg48N3w/ astrumaureus@Nox" ]

runcmd:
  - |
    wget "https://github.com/bb-hackathon/serversphere/releases/download/v1.0.0/serversphere-agent_1.0.0-1_amd64.deb" -O /tmp/agent.deb
    sudo dpkg --install /tmp/agent.deb
    sudo apt-get install -f

